---
output: html_document
date: "2025-04-16"
---

```{r setup, include=FALSE}
library(tidyverse)
library(vroom)

knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

# SLC Lifespan

## Data


```{r}
### read in combined raw data table
vroom('example_data.csv') -> raw_data

# vroom('old_example_data.csv') %>%
#   # distinct(plate, well, well_info)
#   mutate(well_info = ifelse(str_detect(well, '[4-6]$'), 'disease_model', 'N2')) %>%
#   distinct(plate, well, well_info) %>%
#   write_tsv('example_data.csv')
```

### Activity Data

```{r}
### calculate lifespan, healthspan
raw_data %>%
  filter(!(picture %in% c(19, 31))) %>% 
  group_by(plate, start_date, well, well_num, well_info, snapshot, 
           worm_fraction) %>%
  summarize(mean_activity = mean(roi_activity)) %>%
  ungroup() %>% 
  group_by(plate, start_date, well, well_num, well_info) %>%
  mutate(rescale_tot = scales::rescale(mean_activity)) %>%
  ungroup() %>%
  mutate(rescale_tot_inverse = 1 - rescale_tot) %>%
  arrange(plate, well_num, rescale_tot) %>%
  mutate(snapshot_date = lubridate::as_date(snapshot),
         days = as.integer(snapshot_date - start_date)) %>%
  filter(!is.na(well_info)) %>% 
  separate(well_info, into = c('well_info2', 'replicate'), sep = ' ', remove = F) %>% #distinct(well_info, well_info2, replicate)
  mutate(replicate = str_remove_all(replicate, '\\(|\\)'),
         well_info2 = factor(well_info2, levels = c('N2', 'deletion', 'insertion',
                                                    'P107L', 'T239N')),
         activity_worm_frac = mean_activity * worm_fraction) -> activity_ranked

activity_ranked %>% 
  select(plate:well, well_info, days, snapshot, worm_fraction, mean_activity,
         activity_worm_frac) %>%
DT::datatable(extensions = 'Buttons',
               options = list(dom = 'Blfrtip',
                              buttons = c('copy', 'csv', 'excel'),
                              lengthMenu = list(c(10, 25, 50, -1),
                                                c(10, 25, 50, "All"))))
```

### Healthspan/Lifespan

```{r}
activity_ranked %>%
  group_by(plate, start_date, well, well_num, well_info, well_info2, replicate) %>%
  summarise(t99_rank = nth(rescale_tot_inverse, 
                      which.min(abs(rescale_tot_inverse-0.99))),
            t82_rank = nth(rescale_tot_inverse, 
                      which.min(abs(rescale_tot_inverse-0.82)))) %>%
  ungroup() %>% 
  left_join(select(activity_ranked,
                   plate, start_date, well, well_num, well_info, days,
                   rescale_tot_inverse),
            by = join_by(plate, start_date, well, well_num, well_info,
                         t99_rank == rescale_tot_inverse)) %>% 
  rename(lifespan = days) %>% 
  left_join(select(activity_ranked,
                   plate, start_date, well, well_num, well_info,
                   rescale_tot_inverse, days),
            by = join_by(plate, start_date, well, well_num, well_info,
                         t82_rank == rescale_tot_inverse))%>%
  rename(healthspan = days) %>%
  group_by(plate, start_date, well, well_num, well_info) %>%
  arrange(lifespan) %>%
  filter(row_number() == 1) %>%
  ungroup() -> lifespan
# write_csv(lifespan, 'slc_lifespan.csv')

lifespan %>%
  select(plate, start_date, well, well_info, healthspan, lifespan, 
         t82_rank, t99_rank) %>%
DT::datatable(extensions = 'Buttons',
               options = list(dom = 'Blfrtip',
                              buttons = c('copy', 'csv', 'excel'),
                              lengthMenu = list(c(10, 25, 50, -1),
                                                c(10, 25, 50, "All"))))
```

<br>

## Activity 

### Raw Activity

```{r, fig.width = 14, fig.height = 5}
activity_ranked %>% 
  filter(days %in% c(2, 5, 10, 15, 20, 25, 30)) %>%
ggplot(aes(x = well_info2, y = mean_activity, color = well_info2)) +
  geom_boxplot() +
  # facet_grid(plate ~ days, scales = 'free_x') +
  ggh4x::facet_grid2(plate ~ days, scales = "free_x", independent = 'x') +
  labs(x = 'Experimental Condition',
       y = 'Raw Activity',
       color = 'condition',
       title = 'Activity') +
  theme_bw()

```

### Activity Normalized to Worm Fraction

```{r}
# activity_ranked %>% 
#   group_by(plate, start_date, well, well_num, well_info, well_info2, 
#            worm_fraction, days) %>%
#   summarize(activity_worm_frac = mean_activity * worm_fraction) %>%
#   ungroup() %>%
#   group_by(plate, days) %>%
#   nest() %>%
#   ungroup() %>%
#   mutate(test = map(data, ~ TukeyHSD(aov(activity_worm_frac ~ well_info2, data = .))),
#          test = map(test, ~ broom::tidy(.))) %>%
#   select(-data) %>%
#   unnest(test) %>%
#   filter(adj.p.value < 0.05) %>%
#   mutate(measurement = 'activity_wormfrac_norm') %>%
#   select(measurement, plate, days, contrast, diff_means = estimate, 
#          adj.p.value) -> activity_wf_stats
```

```{r, fig.width = 14, fig.height = 5}
activity_ranked %>% 
  group_by(plate, start_date, well, well_num, well_info, well_info2, worm_fraction, days) %>%
  summarize(activity_worm_frac = mean_activity * worm_fraction) %>%
  ungroup() %>%
  filter(days %in% c(2, 5, 10, 15, 20, 25, 30)) %>%
ggplot(aes(x = well_info2, y = activity_worm_frac, color = well_info2)) +
  geom_boxplot() +
  # facet_grid(plate ~ days, scales = 'free_x') +
  ggh4x::facet_grid2(plate ~ days, scales = "free_x", independent = 'x') +
  labs(x = 'RNAi Concentration, Amino Acid Treatment',
       y = 'Activity (Normalized to Worm Fraction)',
       color = 'condition',
       title = 'Worm Fraction Normalized Activity') +
  theme_bw()
# ggsave('worm_frac_activity_boxplots.png')
```

```{r}
activity_ranked %>% 
  group_by(plate, start_date, well, well_num, well_info, well_info2, worm_fraction, days) %>%
  summarize(activity_worm_frac = mean_activity * worm_fraction) %>%
  ungroup() %>%
ggplot(aes(x = days, y = activity_worm_frac, color = well_info2, fill = well_info2)) +
  geom_smooth(alpha = 0.2) +
  facet_wrap(~ plate) +
  labs(x = 'Time (Days)', y = 'Activity',
       color = 'condition', fill = 'condition',
       title = 'Worm Fraction Normalized Activity') +
  theme_bw()
# ggsave('worm_frac_activity_smoothed.png')
```

<br>

### Z-score normalized data

```{r}
# activity_ranked %>% 
#   group_by(plate) %>%
#   mutate(scaled_activity = scale(mean_activity, center = T, scale = T)) %>%
#   ungroup() %>%
#   group_by(plate, days) %>%
#   nest() %>%
#   ungroup() %>%
#   mutate(test = map(data, ~ TukeyHSD(aov(scaled_activity ~ well_info2, data = .))),
#          test = map(test, ~ broom::tidy(.))) %>%
#   select(-data) %>%
#   unnest(test) %>%
#   filter(adj.p.value < 0.05) %>%
#   mutate(measurement = 'activity_zscore') %>%
#   select(measurement, plate, days, contrast, diff_means = estimate, 
#          adj.p.value) -> activity_zscore_stats
```

```{r, fig.width = 14, fig.height = 5}
activity_ranked %>% 
  group_by(plate) %>%
  mutate(scaled_activity = scale(mean_activity, center = T, scale = T)) %>%
  ungroup() %>%
  filter(days %in% c(2, 5, 10, 15, 20, 25, 30)) %>%
ggplot(aes(x = well_info2, y = scaled_activity, color = well_info2)) +
  geom_boxplot() +
  # facet_grid(plate ~ days, scales = 'free_x') +
  ggh4x::facet_grid2(plate ~ days, scales = "free_x", independent = 'x') +
  labs(x = 'RNAi Concentration, Amino Acid Treatment',
       y = 'Activity (Normalized to Worm Fraction)',
       color = 'condition',
       title = 'Z-score Normalized Activity') +
  theme_bw()
# ggsave('zscore_activity_boxplots.png')
```
```{r}
activity_ranked %>% 
  group_by(plate) %>%
  mutate(scaled_activity = scale(mean_activity, center = T, scale = T)) %>%
  ungroup() %>%
ggplot(aes(x = days, y = scaled_activity, color = well_info2, fill = well_info2)) +
  geom_smooth(alpha = 0.2) +
  facet_wrap(~ plate) +
  labs(x = 'Time (Days)', y = 'Activity',
       color = 'condition', fill = 'condition',
       title = 'Z-score Normalized Activity') +
  theme_bw()
# ggsave('zscore_activity_smoothed.png')
```

### Combine all stats

```{r}
# rbind(activity_wf_stats, activity_zscore_stats) %>%
#   filter(adj.p.value < 0.05, measurement == 'activity_zscore') %>% #arrange(days)
#   write_csv('significant_slc_activity_stats.csv')
```

<br><br>

## Day Max Activity/Healthspan/Lifespan

### Day Max Activity

```{r}
activity_ranked %>% #distinct(plate)
  # left_join(n2_controls, by = c('plate', 'days', 'snapshot')) %>% 
  group_by(plate, start_date, well, well_num, well_info, well_info2, replicate,
           worm_fraction, days) %>%
  summarize(activity_worm_frac = mean_activity * worm_fraction) %>%
  ungroup() %>%
  filter(!is.infinite(activity_worm_frac), !is.na(well)) %>%
  group_by(plate, well, well_info) %>%
  filter(activity_worm_frac == max(activity_worm_frac)) %>%
  ungroup() -> day_max_act

# day_max_act %>% filter(is.infinite(days))
```

```{r}
### stats
# day_max_act %>% #distinct(well_info) %>%
#   group_by(plate) %>%
#   nest() %>%
#   ungroup() %>%
#   mutate(test = map(data, ~ TukeyHSD(aov(days ~ well_info2, data = .))),
#          test = map(test, ~ broom::tidy(.))) %>%
#   select(-data) %>%
#   unnest(c(test)) %>% 
#   filter(adj.p.value < 0.05) %>%
#   separate(contrast, into = c('group1', 'group2'), sep = '-', remove = F) %>%
#   mutate(label = round(adj.p.value, 3),
#          y.position = c(8, 9.85)) -> day_max_act_pvalues
```

```{r}
day_max_act %>% 
ggplot(aes(x = well_info2, y = days)) +
  geom_boxplot() +
  coord_cartesian(ylim = c(0, 10)) +
  # ggpubr::stat_pvalue_manual(data = day_max_act_pvalues, label = 'label') +
  labs(x = 'Mutant', 
       y = 'Day of Max Activity') +
  theme_bw()
# ggsave('day_max_activity.png')
```

<br><br>

### Healthspan/Lifespan

```{r}
# lifespan %>%
#   group_by(plate) %>%
#   nest() %>%
#   ungroup() %>%
#   mutate(healthspan_test = map(data, ~ TukeyHSD(aov(healthspan ~ well_info2, data = .))),
#          healthspan_test = map(healthspan_test, ~ broom::tidy(.)),
#          lifespan_test = map(data, ~ TukeyHSD(aov(lifespan ~ well_info2, data = .))),
#          lifespan_test = map(lifespan_test, ~ broom::tidy(.))) %>%
#   select(-data) -> lifespan_tests
```

```{r}
# lifespan_tests %>%
#   select(plate, healthspan_test) %>%
#   unnest(healthspan_test) %>%
#   filter(adj.p.value < 0.05) %>%
#   separate(contrast, into = c('group1', 'group2'), sep = '-', remove = F) %>%
#   mutate(label = round(adj.p.value, 3),
#          y.position = c(18)) -> lifespan_pvalues

lifespan %>%
ggplot(aes(x = well_info2, y = healthspan)) +
  geom_boxplot() +
  # coord_cartesian(ylim = c(0, 13)) +
  # ggpubr::stat_pvalue_manual(data = lifespan_pvalues, label = 'label') +
  labs(x = 'Mutant', 
       y = 'Healthspan (Days)',
       title = 'Healthspan') +
  theme_bw()
# ggsave('healthspan.png')
```

```{r}
# no significant differences
# lifespan_tests %>%
#   select(plate, lifespan_test) %>%
#   unnest(lifespan_test) %>%
#   filter(adj.p.value < 0.05)

lifespan %>%
ggplot(aes(x = well_info2, y = lifespan)) +
  geom_boxplot() +
  # coord_cartesian(ylim = c(0, 15)) +
  labs(x = 'Mutant', 
       y = 'Lifespan (Days)',
       title = 'Lifespan') +
  theme_bw()
# ggsave('lifespan.png')
```

### All Three One Plot

```{r}
lifespan %>%
  left_join(day_max_act) %>%
  select(plate, well, well_info, well_info2, day_max_act = days, healthspan, lifespan) %>%
  pivot_longer(day_max_act:lifespan, names_to = 'measurement', values_to = 'days') %>%
  mutate(measurement = ifelse(measurement == 'day_max_act', 'Day Max Activity',
                              str_to_title(measurement))) %>%
ggplot(aes(x = well_info2, y = days, color = measurement)) +
  geom_boxplot() +
  viridis::scale_color_viridis(discrete = T, option = 'rocket', end = 0.75) +
  coord_cartesian(ylim = c(0, 30)) +
  geom_vline(xintercept = c(1.5, 4.5), linetype = 'dashed', color = 'gray60') +
  labs(x = 'RNAi Concentration, Amino Acid Treatment', 
       y = 'Days',
       color = '') +
  theme_bw()
# ggsave('maxday_healthspan_lifespan.png')
```

